import PDFDocument from 'pdfkit';

/**
 * Generates a patient recovery PDF report
 * @param {Object} data - All data required for the report
 * @param {Object} res - Express response object
 */
const generateRecoveryPDF = (data, res) => {
  const {
    patient,
    medicines,
    adherence,
    missedCount,
    symptoms
  } = data;

  const doc = new PDFDocument({ margin: 50 });

  // Set response headers
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename=${patient.name}_Recovery_Report.pdf`
  );

  // Pipe PDF to response
  doc.pipe(res);

  // ---- PDF CONTENT ----

  doc
    .fontSize(20)
    .text('CareCircle Recovery Report', { align: 'center' })
    .moveDown();

  doc
    .fontSize(14)
    .text(`Patient Name: ${patient.name}`)
    .text(`Age: ${patient.age}`)
    .text(`Condition: ${patient.condition}`)
    .moveDown();

  doc
    .fontSize(16)
    .text('Medicine Adherence Summary')
    .moveDown(0.5);

  doc
    .fontSize(12)
    .text(`Adherence Percentage: ${adherence}%`)
    .text(`Missed Doses: ${missedCount}`)
    .moveDown();

  doc
    .fontSize(16)
    .text('Medicines')
    .moveDown(0.5);

  medicines.forEach((med, index) => {
    doc
      .fontSize(12)
      .text(`${index + 1}. ${med.name}`)
      .text(`   Dosage: ${med.dosage}`)
      .text(`   Schedule: ${med.schedule.join(', ')}`)
      .moveDown(0.5);
  });

  doc.moveDown();

  doc
    .fontSize(16)
    .text('Recent Symptoms')
    .moveDown(0.5);

  if (symptoms.length === 0) {
    doc.fontSize(12).text('No symptoms recorded.');
  } else {
    symptoms.forEach((symptom, index) => {
      doc
        .fontSize(12)
        .text(`${index + 1}. Pain Level: ${symptom.painLevel}/10`)
        .text(`   Temperature: ${symptom.temperature}`)
        .text(`   Notes: ${symptom.notes || 'N/A'}`)
        .text(`   Date: ${new Date(symptom.createdAt).toDateString()}`)
        .moveDown(0.5);
    });
  }

  // Footer
  doc
    .moveDown(2)
    .fontSize(10)
    .text(
      'Generated by CareCircle — Home Recovery Coordination System',
      { align: 'center' }
    );

  // Finalize PDF
  doc.end();
};

export default generateRecoveryPDF;